Repository carch-org/docs, pull requests merged in 2025-07, with the labels that each got.

#52 chore: update commands
  docs/ar/getting-started/installation.md
  docs/ar/reference/commands.md
  docs/de/getting-started/installation.md
  docs/de/reference/commands.md
  docs/es/getting-started/installation.md
  docs/es/reference/commands.md
  docs/fr/getting-started/installation.md
  docs/fr/reference/commands.md
  docs/getting-started/installation.md
  docs/hi/getting-started/installation.md
  docs/hi/reference/commands.md
  docs/ko/getting-started/installation.md
  docs/ko/reference/commands.md
  docs/ne/getting-started/installation.md
  docs/ne/reference/commands.md
  docs/reference/commands.md
  docs/ru/getting-started/installation.md
  docs/ru/reference/commands.md
  docs/zh/getting-started/installation.md
  docs/zh/reference/commands.md
Labels: documentation, update

#53 adding xtask
  docs/ar/project/contributing.md
  docs/de/project/contributing.md
  docs/es/project/contributing.md
  docs/fr/project/contributing.md
  docs/hi/project/contributing.md
  docs/ko/project/contributing.md
  docs/ne/project/contributing.md
  docs/project/contributing.md
  docs/ru/project/contributing.md
  docs/zh/project/contributing.md
Labels: enhancement, update

#58 ui: Add vitepress-theme-tui
  bun.lock
  docs/.vitepress/config.ts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.ts
  package.json
Labels: ui/ux

#59 chore(theme): rounded borders
  bun.lock
  docs/.vitepress/theme/custom.css
  package.json
Labels: ui/ux

#63 feat: add themes
  docs/ar/index.md
  docs/de/index.md
  docs/es/index.md
  docs/fr/index.md
  docs/hi/index.md
  docs/index.md
  docs/ko/index.md
  docs/ne/index.md
  docs/public/archx.png
  docs/public/catppuccin-mocha.png
  docs/public/dracula.png
  docs/public/gruvbox.png
  docs/public/help-preview.png
  docs/public/linux.webp
  docs/public/nord.png
  docs/public/rose-pine.png
  docs/ru/index.md
  docs/zh/index.md
Labels: enhancement, ui/ux
